import dotenv from "dotenv"
import mongoose from "mongoose"
import connectDB from "./config/db.js"
import Product from "./models/Product.js"
import Vendor from "./models/Vendor.js"

dotenv.config()
connectDB()

const products = [
  {
    name: "iPhone 15 Pro Max",
    price: 850000,
    oldPrice: 950000,
    rating: 4.8,
    reviews: 124,
    category: "Phones",
    vendor: "TechZone Lagos",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop",
    badge: "Hot",
    inStock: true,
  },
  {
    name: 'Samsung 4K Smart TV 55"',
    price: 420000,
    oldPrice: 500000,
    rating: 4.6,
    reviews: 89,
    category: "Electronics",
    vendor: "ElectroMart Abuja",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&h=400&fit=crop",
    badge: "Sale",
    inStock: true,
  },
  {
    name: "Sony WH-1000XM5 Headphones",
    price: 185000,
    oldPrice: null,
    rating: 4.9,
    reviews: 210,
    category: "Audio",
    vendor: "SoundHub PH",
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&h=400&fit=crop",
    badge: "Top Rated",
    inStock: true,
  },
  {
    name: 'MacBook Pro M3 14"',
    price: 1200000,
    oldPrice: 1350000,
    rating: 4.9,
    reviews: 76,
    category: "Laptops",
    vendor: "AppleWorld Lagos",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
    badge: "Sale",
    inStock: true,
  },
  {
    name: "Nike Air Jordan 1 Retro",
    price: 65000,
    oldPrice: 80000,
    rating: 4.7,
    reviews: 305,
    category: "Fashion",
    vendor: "SneakerKing Ibadan",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    badge: "Sale",
    inStock: true,
  },
  {
    name: "Canon EOS R50 Camera",
    price: 320000,
    oldPrice: null,
    rating: 4.5,
    reviews: 42,
    category: "Cameras",
    vendor: "PhotoPro Lagos",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop",
    badge: "New",
    inStock: true,
  },
  {
    name: "Apple Watch Series 9",
    price: 280000,
    oldPrice: 320000,
    rating: 4.7,
    reviews: 158,
    category: "Watches",
    vendor: "TechZone Lagos",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&h=400&fit=crop",
    badge: "Sale",
    inStock: false,
  },
  {
    name: "Adidas Ultraboost 23",
    price: 55000,
    oldPrice: null,
    rating: 4.4,
    reviews: 89,
    category: "Fashion",
    vendor: "SneakerKing Ibadan",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&h=400&fit=crop",
    badge: null,
    inStock: true,
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    price: 780000,
    oldPrice: 850000,
    rating: 4.7,
    reviews: 95,
    category: "Phones",
    vendor: "TechZone Lagos",
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=400&fit=crop",
    badge: "Sale",
    inStock: true,
  },
  {
    name: "Dell XPS 15 Laptop",
    price: 980000,
    oldPrice: null,
    rating: 4.6,
    reviews: 54,
    category: "Laptops",
    vendor: "ElectroMart Abuja",
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&h=400&fit=crop",
    badge: "New",
    inStock: true,
  },
  {
    name: "JBL Flip 6 Speaker",
    price: 45000,
    oldPrice: 55000,
    rating: 4.5,
    reviews: 178,
    category: "Audio",
    vendor: "SoundHub PH",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    badge: "Sale",
    inStock: true,
  },
  {
    name: "Gym Dumbbell Set 20kg",
    price: 35000,
    oldPrice: null,
    rating: 4.3,
    reviews: 67,
    category: "Fitness",
    vendor: "FitGear Abuja",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop",
    badge: null,
    inStock: true,
  },
  {
    name: "Nikon Z50 Mirrorless Camera",
    price: 450000,
    oldPrice: 520000,
    rating: 4.6,
    reviews: 33,
    category: "Cameras",
    vendor: "PhotoPro Lagos",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
    badge: "Sale",
    inStock: true,
  },
  {
    name: "Leather Sofa Set 3+2",
    price: 320000,
    oldPrice: null,
    rating: 4.4,
    reviews: 29,
    category: "Home & Living",
    vendor: "HomeDecor Lagos",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop",
    badge: "New",
    inStock: true,
  },
  {
    name: "Garmin Forerunner 255",
    price: 195000,
    oldPrice: 220000,
    rating: 4.8,
    reviews: 112,
    category: "Watches",
    vendor: "TechZone Lagos",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    badge: "Hot",
    inStock: true,
  },
  {
    name: "Zara Oversized Blazer",
    price: 28000,
    oldPrice: null,
    rating: 4.2,
    reviews: 445,
    category: "Fashion",
    vendor: "StyleHub Lagos",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop",
    badge: null,
    inStock: true,
  },
]

const vendors = [
  {
    name: "TechZone Lagos",
    slug: "techzone-lagos",
    category: "Electronics & Gadgets",
    location: "Lagos Island, Lagos",
    rating: 4.8,
    reviews: 412,
    sales: 1200,
    joined: "2021",
    verified: true,
    description: "Nigeria's leading electronics retailer. We stock the latest smartphones, laptops, smartwatches and accessories from top global brands. All products are original with full warranty.",
    banner: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=300&fit=crop",
    avatar: "TZ",
    color: "bg-blue-600",
  },
  {
    name: "ElectroMart Abuja",
    slug: "electromart-abuja",
    category: "Electronics & Home Appliances",
    location: "Wuse 2, Abuja",
    rating: 4.6,
    reviews: 289,
    sales: 890,
    joined: "2022",
    verified: true,
    description: "Your one-stop shop for home appliances and electronics in Abuja. From smart TVs to refrigerators, we deliver quality products at competitive prices nationwide.",
    banner: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=300&fit=crop",
    avatar: "EM",
    color: "bg-purple-600",
  },
  {
    name: "SoundHub PH",
    slug: "soundhub-ph",
    category: "Audio & Music Equipment",
    location: "Port Harcourt, Rivers",
    rating: 4.9,
    reviews: 534,
    sales: 2100,
    joined: "2020",
    verified: true,
    description: "Port Harcourt's premium audio equipment store. Specializing in headphones, speakers, studio equipment and everything audio. Trusted by music lovers and professionals alike.",
    banner: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=300&fit=crop",
    avatar: "SH",
    color: "bg-yellow-600",
  },
  {
    name: "AppleWorld Lagos",
    slug: "appleworld-lagos",
    category: "Apple Products & Accessories",
    location: "Victoria Island, Lagos",
    rating: 4.9,
    reviews: 198,
    sales: 650,
    joined: "2021",
    verified: true,
    description: "Lagos's most trusted Apple reseller. We stock genuine MacBooks, iPhones, iPads, Apple Watches and all accessories. All products come with official Apple warranty.",
    banner: "https://images.unsplash.com/photo-1491933382434-500287f9b54b?w=800&h=300&fit=crop",
    avatar: "AW",
    color: "bg-gray-700",
  },
  {
    name: "SneakerKing Ibadan",
    slug: "sneakerking-ibadan",
    category: "Footwear & Fashion",
    location: "Bodija, Ibadan",
    rating: 4.7,
    reviews: 723,
    sales: 3400,
    joined: "2020",
    verified: true,
    description: "Ibadan's biggest sneaker and fashion store. We carry authentic Nike, Adidas, Jordan and other top brands. From streetwear to luxury fashion, we've got you covered.",
    banner: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=300&fit=crop",
    avatar: "SK",
    color: "bg-orange-600",
  },
  {
    name: "PhotoPro Lagos",
    slug: "photopro-lagos",
    category: "Cameras & Photography",
    location: "Ikeja, Lagos",
    rating: 4.5,
    reviews: 167,
    sales: 420,
    joined: "2022",
    verified: true,
    description: "Professional cameras, lenses and photography equipment. We serve both hobbyists and professional photographers. Also offering camera repairs and photography training.",
    banner: "https://images.unsplash.com/photo-1452780212461-47aef4e35654?w=800&h=300&fit=crop",
    avatar: "PP",
    color: "bg-teal-600",
  },
  {
    name: "FitGear Abuja",
    slug: "fitgear-abuja",
    category: "Fitness & Sports Equipment",
    location: "Garki, Abuja",
    rating: 4.3,
    reviews: 98,
    sales: 310,
    joined: "2023",
    verified: false,
    description: "Everything you need for your fitness journey. Dumbbells, resistance bands, yoga mats, treadmills and more. We help Abuja stay fit one product at a time.",
    banner: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=300&fit=crop",
    avatar: "FG",
    color: "bg-green-600",
  },
  {
    name: "StyleHub Lagos",
    slug: "stylehub-lagos",
    category: "Fashion & Clothing",
    location: "Lekki Phase 1, Lagos",
    rating: 4.2,
    reviews: 445,
    sales: 1800,
    joined: "2022",
    verified: true,
    description: "Lagos's trendiest fashion destination. We curate the latest styles from international and local designers. From casual wear to corporate fashion, express yourself with StyleHub.",
    banner: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=300&fit=crop",
    avatar: "SL",
    color: "bg-pink-600",
  },
  {
    name: "HomeDecor Lagos",
    slug: "homedecor-lagos",
    category: "Home & Living",
    location: "Surulere, Lagos",
    rating: 4.4,
    reviews: 201,
    sales: 560,
    joined: "2021",
    verified: true,
    description: "Transform your living space with our premium furniture and home decor collection. Sofas, beds, dining sets, lighting and accessories. Free delivery within Lagos.",
    banner: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=300&fit=crop",
    avatar: "HD",
    color: "bg-red-600",
  },
]

const seedDB = async () => {
  try {
    // Clear existing data
    await Product.deleteMany()
    await Vendor.deleteMany()
    console.log("🗑️  Existing data cleared")

    // Insert fresh data
    await Product.insertMany(products)
    await Vendor.insertMany(vendors)
    console.log("Products and Vendors seeded successfully!")

    mongoose.connection.close()
    process.exit(0)
  } catch (error) {
    console.error("Seeding failed:", error.message)
    process.exit(1)
  }
}

seedDB()